apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  enterprise.properties: |
    {{- range $key, $val := .Values.configmap }}
    {{ $key }}={{ $val | quote }}
    {{- end }}
