name: Deploy Enterprise Backend

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'Dockerfile'

jobs:
  deploy:
    name: Deploy enterprise-backend
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build enterprise-backend
        run: |
          echo "Building enterprise-backend..."
          docker build -t us-central1-docker.pkg.dev/devops-438908/gcf-artifacts/enterprise-be:${{ github.sha }} .

      - name: Push image
        run: |
          echo "Pushing image for enterprise-backend..."
          docker push us-central1-docker.pkg.dev/devops-438908/gcf-artifacts/enterprise-be:${{ github.sha }}

      - name: Deploy enterprise-backend to Kubernetes
        run: |
          echo "Deploying enterprise-backend..."
          helm upgrade enterprise-backend cmrcs_enterprise_backend-1.0.0.tgz \
            --install \
            --namespace production \
            --reuse-values \
            --set image.tag=${{ github.sha }}
