name: Deploy Enterprise Backend
on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/local-runner.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'Dockerfile'
jobs:
  deploy:
    name: Deploy enterprise-backend
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build enterprise-backend
        run: |
          echo "Building enterprise-backend..."
          # docker build -t us-central1-docker.pkg.dev/devops-438908/gcf-artifacts/enterprise-be:${{ github.sha }} ."

      - name: Push image
        run: |
          echo "Pushing image for enterprise-backend..."
          # docker push us-central1-docker.pkg.dev/devops-438908/gcf-artifacts/enterprise-be:${{ github.sha }}"


      - name: Deploy enterprise-backend to Kubernetes
        run: |
          helm upgrade enterprise-backend ./helm/cmrcs_enterprise_backend \
            --install \
            --reuse-values \
            --set image.tag=${{ github.sha }}

     
